name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Check gradle wrapper
      run: |
        ls -la gradle/wrapper/
        echo "CLASSPATH check"
        echo $CLASSPATH
        
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      env:
        GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk 